class StockMapsSuicidal extends MapAchievementsBase;

defaultproperties {
    packName= "Stock Maps - Suicidal"
    requiredDifficulty= 5.0

    achievements(0)=(title="Suicidal Pub Crawl",description="Win a medium or long game on West London on Suicidal difficulty",image=Texture'KillingFloorHUD.Achievements.Achievement_12')
    achievements(1)=(title="Emperor of the Manor",description="Win a medium or long game on Manor on Suicidal difficulty",image=Texture'KillingFloorHUD.Achievements.Achievement_12')
    achievements(2)=(title="Alligator Farmer",description="Win a medium or long game on Farm on Suicidal difficulty",image=Texture'KillingFloorHUD.Achievements.Achievement_14')
    achievements(3)=(title="Mad Boss",description="Win a medium or long game on Offices on Suicidal difficulty",image=Texture'KillingFloorHUD.Achievements.Achievement_15')
    achievements(4)=(title="Lab Professor",description="Win a medium or long game on Biotics Lab on Suicidal difficulty",image=Texture'KillingFloorHUD.Achievements.Achievement_16')
    achievements(5)=(title="Man of Steel",description="Win a medium or long game on Foundry on Suicidal difficulty",image=Texture'KillingFloor2HUD.Achievements.Achievement_46')
    achievements(6)=(title="Complete Barking",description="Win a medium or long game on Bedlam on Suicidal difficulty",image=Texture'KillingFloor2HUD.Achievements.Achievement_49')
    achievements(7)=(title="Bear King of the Dark Forrest",description="Win a medium or long game on Wyre on Suicidal difficulty",image=Texture'KillingFloor2HUD.Achievements.Achievement_52')
    achievements(8)=(title="Waste of Space",description="Win a medium or long game on Biohazard on Suicidal difficulty",image=Texture'KillingFloor2HUD.Achievements.Achievement_75')
    achievements(9)=(title="Warehouse Foreman",description="Win a medium or long game on Crash on Suicidal difficulty",image=Texture'KillingFloor2HUD.Achievements.Achievement_79')
    achievements(10)=(title="Departure Gate",description="Win a medium or long game on Departed on Suicidal difficulty",image=Texture'KillingFloor2HUD.Achievements.Achievement_83')
    achievements(11)=(title="Train Wreck",description="Win a medium or long game on Filth's Cross on Suicidal difficulty",image=Texture'KillingFloor2HUD.Achievements.Achievement_87')
    achievements(12)=(title="I'm Dying Here!",description="Win a medium or long game on Hospital Horrors on Suicidal difficulty",image=Texture'KillingFloor2HUD.Achievements.Achievement_91')
    achievements(13)=(title="Iceberg",description="Win a medium or long game on Icebreaker on Suicidal difficulty",image=Texture'KillingFloor2HUD.Achievements.Achievement_95')
    achievements(14)=(title="Mountaineer",description="Win a medium or long game on Mountain Pass on Suicidal difficulty",image=Texture'KillingFloor2HUD.Achievements.Achievement_99')
    achievements(15)=(title="Vigilante",description="Win a medium or long game on Suburbia on Suicidal difficulty",image=Texture'KillingFloor2HUD.Achievements.Achievement_103')
    achievements(16)=(title="Pressure Failure",description="Win a medium or long game on Waterworks on Suicidal difficulty",image=Texture'KillingFloor2HUD.Achievements.Achievement_107')
    achievements(17)=(title="I'm Dreaming of a Red Christmas",description="Win a medium or long game on Santa's Evil Lair on Suicidal difficulty",image=Texture'KillingFloor2HUD.Achievements.Achievement_116')
    achievements(18)=(title="This is a Triupmh",description="Win a medium or long game on Aperture on Suicidal difficulty",image=Texture'KillingFloor2HUD.Achievements.Achievement_135')
    achievements(19)=(title="3 Ring Circus",description="Win a medium or long game on Abusement Park on Suicidal difficulty",image=Texture'KillingFloor2HUD.Achievements.Achievement_140')
    achievements(20)=(title="On The Rocks",description="Win a medium or long game on Ice Cave on Suicidal difficulty",image=Texture'KillingFloor2HUD.Achievements.Achievement_173')
    achievements(21)=(title="Demoic Road",description="Win a medium or long game on Hellride on Suicidal difficulty",image=Texture'KillingFloor2HUD.Achievements.Achievement_183')
    achievements(22)=(title="First Coustins (Once Removed)",description="Win a medium or long game on Hillbilly Horror on Suicidal difficulty",image=Texture'KillingFloor2HUD.Achievements.Achievement_191')
    achievements(23)=(title="Amusing Death",description="Win a medium or long game on Moonbase on Suicidal difficulty",image=Texture'KillingFloor2HUD.Achievements.Achievement_206')
    achievements(24)=(title="Fractional Neutron Activator",description="Win a medium or long game on Steamland on Suicidal difficulty",image=Texture'KillingFloor2HUD.Achievements.Achievement_211')
    achievements(25)=(title="Alpha Wave Osteooxidation Activator",description="Win Steamland in Objective Mode on Suicidal difficulty",image=Texture'KillingFloor2HUD.Achievements.Achievement_215')
    achievements(26)=(title="Stevedore",description="Win a medium or long game on Fright Yard on Suicidal difficulty",image=Texture'KillingFloor2HUD.Achievements.Achievement_230')
    achievements(27)=(title="Crane Operator",description="Win Fright Yard in Objective Mode on Suicidal difficulty",image=Texture'KillingFloor2HUD.Achievements.Achievement_234')
    achievements(28)=(title="Cerberus",description="Win a medium or long game on Hell on Suicidal difficulty",image=Texture'KillingFloor2HUD.Achievements.Achievement_245')
    achievements(29)=(title="Amnesia",description="Win a medium or long game on Forgotton on Suicidal difficulty",image=Texture'KillingFloor2HUD.Achievements.Achievement_249')
    achievements(30)=(title="Master Brewer",description="Win a medium or long game on Siren's Belch on Suicidal difficulty",image=Texture'KillingFloor2HUD.Achievements.Achievement_254')
    achievements(31)=(title="Prince",description="Win a medium or long game on Stronghold on Suicidal difficulty",image=Texture'KillingFloor2HUD.Achievements.Achievement_258')
    achievements(32)=(title="Business Class",description="Win a medium or long game on Transit on Suicidal difficulty",image=Texture'KillingFloor2HUD.Achievements.Achievement_262')
    achievements(33)=(title="Serious vacation",description="Win Transit in Objective Mode on Suicidal difficulty",image=Texture'KillingFloor2HUD.Achievements.Achievement_266')
    achievements(34)=(title="Burned out",description="Win a medium or long game on Clandestine on Suicidal difficulty",image=Texture'KillingFloor2HUD.Achievements.Achievement_277')
    achievements(35)=(title="Grotto of Terror",description="Win a medium or long game on ThrillsChills on Suicidal difficulty",image=Texture'KillingFloor2HUD.Achievements.Achievement_282')
}
